#!/bin/bash
RED='\033[0;31m'
NC='\033[0m'
echo "Checking VPS"
clear
echo "---------------------------------------------------"
echo "USERNAME          EXP DATE          STATUS"
echo "---------------------------------------------------"
while read expired
do
AKUN="$(echo $LOGIN | cut -d: -f1)"
ID="$(echo $LOGIN | grep -v nobody | cut -d: -f3)"
exp="$(chage -l $exp | grep "Account expires" | awk -F": " '{print $2}')"
status="$(passwd -S $LOGIN| awk '{print $2}' )"
if [[ $ID -ge 1000 ]]; then
if [[ "$status" = "L" ]]; then
printf "%-17s %2s %-17s %2s \n" "$LOGIN" "$exp     " "${RED}LOCKED${NORMAL}"
else
printf "%-17s %2s %-17s %2s \n" "$LOGIN" "$exp     " "${GREEN}UNLOCKED${NORMAL}"
fi
fi
done < /etc/passwd
ssh="$(awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' /etc/passwd | wc -l)"
echo "---------------------------------------------------"
echo "Account number: $ssh user"
echo "---------------------------------------------------"