#!/bin/bash
dateFromServer=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
biji=`date +"%Y-%m-%d" -d "$dateFromServer"`
###########- COLOR CODE -##############
colornow=$(cat /etc/ssnvpn/theme/color.conf)
RED='\033[0;31m'
NC='\033[0m'
gray="\e[1;30m"
BLUE="\033[36m"
GREEN='\033[0;32m'
grenbo="\e[92;1m"
YELL='\033[0;33m'
BGX="\033[42m"
NC="\e[0m"
RED="\033[0;31m" 
COLOR1="$(cat /etc/ssnvpn/theme/$colornow | grep -w "TEXT" | cut -d: -f2|sed 's/ //g')"
COLBG1="$(cat /etc/ssnvpn/theme/$colornow | grep -w "BG" | cut -d: -f2|sed 's/ //g')"                    
###########- END COLOR CODE -##########

clear
echo -e "${BLUE}┌─────────────────────────────────────────────────┐${NC}"
echo -e "${BLUE}│${NC} ${BGX}             • BACKUP PANEL MENU •             ${NC} ${BLUE}│$NC"
echo -e "${BLUE}└─────────────────────────────────────────────────┘${NC}"
echo -e " ${BLUE}┌───────────────────────────────────────────────┐${NC}"
echo -e " ${BLUE}│$NC   ${GREEN}[01]${NC} • BACKUP VPS      ${GREEN}[03]${NC} • BACKUP API    ${BLUE}│$NC"
echo -e " ${BLUE}│$NC   ${GREEN}[02]${NC} • RESTORE VPS     ${GREEN}[04]${NC} • RESET API     ${BLUE}│$NC"
echo -e " ${BLUE}│$NC                                               ${BLUE}│$NC"
echo -e " ${BLUE}│$NC   ${GREEN}[00]${NC} • GO BACK${NC}                              ${BLUE}│$NC"
echo -e " ${BLUE}└───────────────────────────────────────────────┘${NC}"
echo -e "${BLUE}┌─────────────────────────────────────────────────┐${NC}"
echo -e "${BLUE}│${NC}                 • RIZKIHDYT-PROJECT •                 ${BLUE}│$NC"
echo -e "${BLUE}└─────────────────────────────────────────────────┘${NC}"
echo -e ""
read -p " Select menu :  "  opt
echo -e ""
case $opt in
01 | 1) clear ; backup ;;
02 | 2) clear ; restore ;;
03 | 3) clear ; menu3 ;;
04 | 4) clear ; menu4 ;;
00 | 0) clear ; menu ;;
*) clear ; menu-backup ;;
esac

       
