#!/bin/bash
# COLOR VALIDATION
clear
RED='\033[0;31m'
NC='\033[0m'
gray="\e[1;30m"
Blue="\033[36m"
GREEN='\033[0;32m'
grenbo="\e[92;1m"
YELL='\033[0;33m'
BGX="\033[42m"
ISP=$(cat /etc/xray/isp)
NS=$(cat /etc/xray/dns)
CITY=$(cat /etc/xray/city)
IPVPS=$(curl -s ipv4.icanhazip.com)
domain=$(cat /etc/xray/domain)
RAM=$(free -m | awk 'NR==2 {print $2}')
USAGERAM=$(free -m | awk 'NR==2 {print $3}')
MEMOFREE=$(printf '%-1s' "$(free -m | awk 'NR==2{printf "%.2f%%", $3*100/$2 }')")
LOADCPU=$(printf '%-0.00001s' "$(top -bn1 | awk '/Cpu/ { cpu = "" 100 - $8 "%" }; END { print cpu }')")
MODEL=$(cat /etc/os-release | grep -w PRETTY_NAME | head -n1 | sed 's/=//g' | sed 's/"//g' | sed 's/PRETTY_NAME//g')
CORE=$(printf '%-1s' "$(grep -c cpu[0-9] /proc/stat)")
Exp="Never Expired"
Name="RizkiHdyt Tunnel"
DATEVPS=$(date +'%d/%m/%Y')
TIMEZONE=$(printf '%(%H:%M:%S)T')
SERONLINE=$(uptime -p | cut -d " " -f 2-10000)
if [ ! -e /etc/vmess ]; then
    mkdir -p /etc/vmess
    touch /etc/vmess/.vmess.db
fi
vms=$(cat /etc/vmess/.vmess.db)
if [[ $vms = "" ]]; then
    vm="0"
else
    vm=$(cat /etc/vmess/.vmess.db | grep "###" | wc -l)
fi

if [ ! -e /etc/vless ]; then
    mkdir -p /etc/vless
    touch /etc/vless/.vless.db
fi
vms=$(cat /etc/vless/.vless.db)
if [[ $vms = "" ]]; then
    vl="0"
else
    vl=$(cat /etc/vless/.vless.db | grep "###" | wc -l)
fi

if [ ! -e /etc/trojan ]; then
    mkdir -p /etc/trojan
    touch /etc/trojan/.trojan.db
fi
vms=$(cat /etc/trojan/.trojan.db)
if [[ $vms = "" ]]; then
    tr="0"
else
    tr=$(cat /etc/trojan/.trojan.db | grep "###" | wc -l)
fi
if [ ! -e /etc/shadowsocks ]; then
    mkdir -p /etc/shadowsocks
    touch /etc/shadowsocks/.shadowsocks.db
fi
vms=$(cat /etc/shadowsocks/.shadowsocks.db)
if [[ $vms = "" ]]; then
    ss="0"
else
    ss=$(cat /etc/shadowsocks/.shadowsocks.db | grep "###" | wc -l)
fi
if [ ! -e /etc/ssh ]; then
    mkdir -p /etc/ssh
    touch /etc/ssh/.ssh.db
fi
vms=$(cat /etc/ssh/.ssh.db)
if [[ $vms = "" ]]; then
    ssh="0"
else
    ssh=$(cat /etc/ssh/.ssh.db | grep "###" | wc -l)
fi
clear
echo -e "\033[1;93m──────────────────────────────────────────\033[0m"
echo -e "\033[36m
╔═╗─╔╦═══╦╗╔╗╔╦══╗╔══╦═══╗╔═══╦═══╦═══╗─╔╦═══╦═══╦════╗
║║╚╗║║╔══╣║║║║║╔╗║╚╣╠╣╔══╝║╔═╗║╔═╗║╔═╗║─║║╔══╣╔═╗║╔╗╔╗║
║╔╗╚╝║╚══╣║║║║║╚╝╚╗║║║╚══╗║╚═╝║╚═╝║║─║║─║║╚══╣║─╚╩╝║║╚╝
║║╚╗║║╔══╣╚╝╚╝║╔═╗║║║║╔══╝║╔══╣╔╗╔╣║─║╠╗║║╔══╣║─╔╗─║║
║║─║║║╚══╬╗╔╗╔╣╚═╝╠╣╠╣╚══╗║║──║║║╚╣╚═╝║╚╝║╚══╣╚═╝║─║║
╚╝─╚═╩═══╝╚╝╚╝╚═══╩══╩═══╝╚╝──╚╝╚═╩═══╩══╩═══╩═══╝─╚╝   \033[36m"
echo -e "\033[1;93m──────────────────────────────────────────\033[0m"
echo -e " ${Blue}System OS${NC}     : \033[0;32m$MODEL${NC}"
echo -e " ${Blue}Server RAM${NC}    : \033[0;32m$RAM MB $NC"
echo -e " ${Blue}Usage RAM${NC}     : \033[0;32m$USAGERAM MB $NC"
echo -e " ${Blue}Usage Memory${NC}  : \033[0;32m$MEMOFREE${NC}"
echo -e " ${Blue}LoadCPU${NC}       : \033[0;32m$LOADCPU%${NC}"
echo -e " ${Blue}Uptime Server${NC} : \033[0;32m$SERONLINE${NC}"
echo -e " ${Blue}Core System${NC}   : \033[0;32m$CORE${NC}"
echo -e " ${Blue}Date${NC}          : \033[0;32m$DATEVPS${NC}"
echo -e " ${Blue}Time${NC}          : \033[0;32m$TIMEZONE${NC}"
echo -e " ${Blue}Isp VPS${NC}       : \033[0;32m$ISP${NC}"
echo -e " ${Blue}City${NC}          : \033[0;32m$CITY${NC}"
echo -e " ${Blue}IP VPS${NC}        : \033[0;32m$IPVPS${NC}"
echo -e " ${Blue}Domain${NC}        : \033[0;32m$domain${NC}"
echo -e " ${Blue}NS Domain${NC}     : \033[0;32m$NS${NC}"
echo -e " ${Blue}Exp Script${NC}    : \033[0;32m$Exp${NC}"
echo -e " ${Blue}Name Author${NC}   : \033[0;32m$Name${NC}"
echo -e "\033[1;93m┌──────────────────────────────────────────┐\033[0m"
echo -e "\033[1;93m│\033[0m ${RED}SSH  VMESS   VLESS  TROJAN   SHADOWSOCKS$NC"
echo -e "\033[1;93m│\033[0m ${Blue}[$ssh]   [$vm]     [$vl]    [$tr]         [$ss]   $NC"
echo -e "\033[1;93m└──────────────────────────────────────────┘\033[0m"
echo -e "\033[1;93m┌──────────────────────────────────────────┐\033[0m"
echo -e "\033[1;93m│  ${Blue}1.${NC} \033[0;36mSSH OVPN MANAGER${NC}"
echo -e "\033[1;93m│  ${Blue}2.${NC} \033[0;36mVMESS MANAGER${NC}"
echo -e "\033[1;93m│  ${Blue}3.${NC} \033[0;36mVLESS MANAGER${NC}"
echo -e "\033[1;93m│  ${Blue}4.${NC} \033[0;36mTROJAN MANAGER${NC}"
echo -e "\033[1;93m│  ${Blue}5.${NC} \033[0;36mSHDWSK MANAGER${NC}"
echo -e "\033[1;93m│  ${Blue}6.${NC} \033[0;36mRUNNING SYSTEM${NC}"
echo -e "\033[1;93m│  ${Blue}7.${NC} \033[0;36mBACKUP & RESTORE${NC}"
echo -e "\033[1;93m│  ${Blue}8.${NC} \033[0;36mPORT VPS INFO${NC}"
echo -e "\033[1;93m│  ${Blue}9.${NC} \033[0;36mLOAD VPS INFO${NC}"
echo -e "\033[1;93m│  ${Blue}10.${NC}\033[0;36mSPEEDTEST${NC}"
echo -e "\033[1;93m│  ${Blue}11.${NC}\033[0;36mCHANGE DOMAIN${NC}"
echo -e "\033[1;93m│  ${Blue}12.${NC}\033[0;36mCHANGE BANNER${NC}"
echo -e "\033[1;93m│  ${Blue}13.${NC}\033[0;36mRESTART SERVICE${NC}"
echo -e "\033[1;93m│  ${Blue}14.${NC}\033[0;36mRESTART SERVER${NC}"
echo -e "\033[1;93m└──────────────────────────────────────────┘\033[0m"
echo -e ""
echo -e "\033[1;93m┌──────────── SETTING ───────────────┐\033[0m"
echo -e "\033[1;93m│  ${Blue}15.${NC} \033[0;36mAUTOREBOOT${NC}"
echo -e "\033[1;93m└──────────────────────────────────────────┘\033[0m"
echo -e ""
read -p "Select From Options [ 1 - 15 ] : " menu
case $menu in
1)
    ssh
    ;;
2)
    vmess
    ;;
3)
    vless
    ;;
4)
    trojan
    ;;
5)
    shadowsocks
    ;;
6)
    run
    ;;
7)
    menu-backup
    ;;
8)
    portin
    ;;
9)
    gotop
    ;;
10)
    clear
    speedtest
    ;;
11)
    get-domain
    ;;
12)
    nano /etc/banner
    ;;
13)
    seres
    ;;
14)
    reboot
    ;;

15)
    autokill
    ;;
14)
    auto-reboot
    ;;
*)
    menu
    ;;
esac
